version: '3.7'
services:
  # registry:
  #   image: registry:2
  # artifact-registry:
  #   container_name: artifact-registry
  #   image: ghcr.io/t1mt/artifact-registry:sha-cd15bba7
  #   environment:
  #     ARTIFACT_REGISTRY_AES_KEY: "aaa"
  #   command:
  #   - --backend=10.246.142.214:30500
  #   - --insecure
  #   - --debug
  #   ports:
  #   - "9887:9887"
  artifact-registry-client:
    container_name: artifact-registry-client
    image: ghcr.io/t1mt/artifact-registry:sha-cd15bba7
    init: true
    entrypoint: ["/bin/sh", "-c"]
    command:
    - sleep infinity
